GET http://localhost:8081/favorites/josue1
###
POST http://localhost:8081/favorites/create
Content-Type: application/json

{
    "username": "josue2",
    "favoriteName": null,
    "direction" : "inbound"
}
###